name: Docker Image CI

on: [push, pull_request]

jobs:
  build_app_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build base.alpine --file Dockerfile
      
  build_go_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build build.go --file Dockerfile
          
      
